# Python Programmging Practice I: Medical Image Processing
### Sina Dabiri
### sdabiri3@gatech.edu
### sdabiri@emory.edu

## Q1: Numpy

In [1]:
import numpy as np

### a.Generate a pseudo-random numpy vector arr_1 with 5 numbers, each of which is between 0 and 1. Print arr_1. You must use a numpy seed value of 123. Make sure the “random” numbers remain the same every time you run the code.

In [4]:
np.random.seed(123)
arr_1 = np.random.rand(5)
print (arr_1)

[0.69646919 0.28613933 0.22685145 0.55131477 0.71946897]


### b. Given an additional vector arr_2 as [0 1 2 3 4 5 6 7 8 9]. Please perform 1D convolution of arr_1 * arr_2 using a for loop. Print the result. You cannot use numpy.convolve().

$ y = x * w \rightarrow y[i]= \sum_{k=0}^{(m-1)} x[i+m-k]w[k] $

$ y = arr_1 * arr_2 \rightarrow y[i]= \sum_{k=0}^{(m-1)} arr_1[i+m-k] arr_2[k] $

In [8]:
arr_2 = [0,1,2,3,4,5,6,7,8,9]
arr_2_reverse = np.array(arr_2[::-1])
print("The second array in reverse is: ", arr_2_reverse)

# p: size of padding
p = arr_2_reverse.shape[0]-1 # padding of 4
zeros = np.zeros(p)
arr_1_padded = np.concatenate([zeros, arr_1, zeros])
print("The first array with padding is: ", arr_1_padded)
y = np.empty(len(arr_1_padded) - len(arr_2_reverse) + 1)

The second array in reverse is:  [9 8 7 6 5 4 3 2 1 0]
The first array with padding is:  [0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.69646919 0.28613933 0.22685145
 0.55131477 0.71946897 0.         0.         0.         0.
 0.         0.         0.         0.         0.        ]


In [10]:
arr_1_padded[0:0+arr_2_reverse.shape[0]]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.69646919])

In [27]:
# n: size of array 1
# m: size of array 2
n_p = arr_1_padded.shape[0] # n+2p
print("Size of array 1 padded: ", n_p)
m = arr_2_reverse.shape[0]
print("size of array 2: ", m)

Size of array 1 padded:  23
size of array 2:  10


In [33]:
# output_size:[n+2p-m]+1 
output_size = n_p-m+1
print("The convolution output size: ", output_size)

The convolution output size:  14


In [31]:
for c in range(0, output_size):
    y[c] = np.sum(arr_1_padded[c:c + arr_2_reverse.shape[0]] * arr_2_reverse)

print("The convolution result is: ", y)

The convolution result is:  [ 0.          0.69646919  1.67907771  2.88853768  4.64931242  7.12955614
  9.60979985 12.09004356 14.57028728 17.05053099 12.56608285 11.48846402
 10.71758468  6.47522073]


In [23]:
# Checking the answer:
d = np.convolve(arr_1, arr_2)
print(d)

[ 0.          0.69646919  1.67907771  2.88853768  4.64931242  7.12955614
  9.60979985 12.09004356 14.57028728 17.05053099 12.56608285 11.48846402
 10.71758468  6.47522073]


### C. Repeat your implementation for arr_2 * arr_1. Compare the results and comment on the finding.

In [35]:
arr_1_reverse = np.array(arr_1[::-1])
print("array 1 in reverse order: ", arr_1_reverse)

array 1 in reverse order:  [0.71946897 0.55131477 0.22685145 0.28613933 0.69646919]


In [37]:
# p: size of padding
p2 = arr_1_reverse.shape[0]-1 # padding of 4
zeros = np.zeros(p2)
arr_2_padded = np.concatenate([zeros, arr_2, zeros])
print("The array 2 with padding is: ", arr_2_padded)

The array 2 with padding is:  [0. 0. 0. 0. 0. 1. 2. 3. 4. 5. 6. 7. 8. 9. 0. 0. 0. 0.]


In [41]:
# n: size of array 1
# m: size of array 2
n_p2 = arr_2_padded.shape[0] # n+2p
print("Size of array 2 padded: ", n_p2)
m2 = arr_1_reverse.shape[0]
print("size of array 1: ", m2)

y2 = np.empty(n_p2 - m2 + 1)

Size of array 2 padded:  18
size of array 1:  5


In [43]:
# output_size:[n+2p-m]+1 
output_size2 = n_p2-m2+1
print("The convolution output size: ", output_size2)

The convolution output size:  14


In [45]:
for c in range(0, output_size2):
    y2[c] = np.sum(arr_2_padded[c:c + arr_1_reverse.shape[0]] * arr_1_reverse)

print("The convolution result is: ", y2)

The convolution result is:  [ 0.          0.69646919  1.67907771  2.88853768  4.64931242  7.12955614
  9.60979985 12.09004356 14.57028728 17.05053099 12.56608285 11.48846402
 10.71758468  6.47522073]


In [47]:
# check answer:

d2 = np.convolve(arr_2, arr_1)
print(d2)

[ 0.          0.69646919  1.67907771  2.88853768  4.64931242  7.12955614
  9.60979985 12.09004356 14.57028728 17.05053099 12.56608285 11.48846402
 10.71758468  6.47522073]


#### The results are the same, which makes sense it doesn't matter the order of flipping and moving which array across, the individual number multiplication and summation results in the same answer. 

### d. 2D cross-correlation function: 6x5 array (np.random.randint(10)) and 3x3 kernel. Infer padding and stride based on the given information.

In [60]:
arr_3 = np.empty((6,5))
arr_3 = [np.random.randint(0,10) for i in range(30)]
arr_3 = np.reshape(arr_3,(6,5))
print("The third array is: ",arr_3)

The third array is:  [[6 2 1 8 3]
 [5 0 2 6 2]
 [4 4 6 3 0]
 [6 4 7 6 7]
 [1 5 7 9 2]
 [4 8 1 2 1]]


In [64]:
arr_4 = np.array([[0,-1,-1],[-1,9,2],[-1,-1,-1]])
print("The array 4 is: ", arr_4)

The array 4 is:  [[ 0 -1 -1]
 [-1  9  2]
 [-1 -1 -1]]


In [94]:
# p_2d: size of padding is zero, since output is smaller than input
p_2d = 0 # padding of 4
print("Padding size is: ", p_2d)
zeros_r = np.zeros((p_2d,arr_3.shape[1]))
print("padding zeros row are: ", zeros_r)

arr_3_padded_r = np.concatenate([zeros_r, arr_3, zeros_r],axis=0)

zeros_c = np.zeros((p_2d,arr_3_padded_r.shape[0])).transpose()
print("padding zeros column are: ", zeros_c)
arr_3_padded = np.concatenate([zeros_c, arr_3_padded_r, zeros_c],axis=1)
print("The array 3 with padding is: ", arr_3_padded)

Padding size is:  0
padding zeros row are:  []
padding zeros column are:  []
The array 3 with padding is:  [[6. 2. 1. 8. 3.]
 [5. 0. 2. 6. 2.]
 [4. 4. 6. 3. 0.]
 [6. 4. 7. 6. 7.]
 [1. 5. 7. 9. 2.]
 [4. 8. 1. 2. 1.]]


In [96]:
# nxm: size of array 3
# kxl: size of array 4
n_p,m_p = arr_3_padded.shape # n+2p
print("Size of array 3 padded: ", n_p,m_p)
k,l = arr_4.shape
print("size of array 4: ", k,l)

Size of array 3 padded:  6 5
size of array 4:  3 3


In [106]:
y_2d = np.empty((n_p - k + 1,m_p-l+1))
print(np.shape(y_2d))

(4, 3)


In [120]:
# output_size:[n+2p-m]+1 
output_size_2d = (n_p-k+1,m_p-l+1)
print("The convolution output size: ", output_size_2d)

The convolution output size:  (4, 3)


In [110]:
for i in range(0, output_size_2d[0]):
    for j in range(0, output_size_2d[1]):
        y_2d[i,j] = np.sum(arr_3_padded[i:i + arr_4.shape[0],j:j + arr_4.shape[1]] * arr_4)

print("The convolution result is: ", y_2d)

The convolution result is:  [[-18.   8.  36.]
 [ 25.  31.  -7.]
 [ 21.  41.  40.]
 [ 34.  52.  61.]]


In [128]:
from scipy.signal import correlate2d

In [136]:
# check answer:

answer = correlate2d(arr_3, arr_4,mode='valid')
print(np.shape(answer))
print(answer)

(4, 3)
[[-18   8  36]
 [ 25  31  -7]
 [ 21  41  40]
 [ 34  52  61]]
